# Generated by Django 4.1.3 on 2022-11-24 16:36

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import open_movie_data_base.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[open_movie_data_base.utils.validators.CharValidator('^[A-Za-z\\w.-]+\\Z', 'Movie title may contain only latin letters, numbers, and dashes between characters.')])),
                ('release_date', models.DateField()),
                ('age_restriction', models.PositiveIntegerField()),
                ('description', models.CharField(error_messages={'max_length': 'Movie description can only be 600 characters', 'min_length': 'Movie description must be at least 150 characters'}, help_text='The first 30 characters will be displayed as short description', max_length=600, validators=[django.core.validators.MinLengthValidator(150)])),
                ('movie_poster', cloudinary.models.CloudinaryField(max_length=255)),
                ('genres', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('musicals', 'Musicals'), ('mystery', 'Mystery'), ('romance', 'Romance'), ('science', 'Science'), ('fiction', 'Fiction'), ('sports', 'Sports'), ('thriller', 'Thriller'), ('Western', 'Western')], max_length=9)),
                ('movie_length', models.PositiveIntegerField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
