# Generated by Django 4.1.3 on 2022-12-06 12:18

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import open_movie_data_base.movie.validators
import open_movie_data_base.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, validators=[open_movie_data_base.utils.validators.CharValidator('^[\\s\\w.-]+\\Z', 'Movie title may contain only latin letters, numbers, and dashes between characters.')])),
                ('release_date', models.DateField()),
                ('age_restriction', models.PositiveIntegerField()),
                ('description', models.CharField(error_messages={'max_length': 'Movie description can only be 1200 characters', 'min_length': 'Movie description must be at least 300 characters'}, help_text='The first 40 characters will be displayed as short description', max_length=1200, validators=[django.core.validators.MinLengthValidator(300)])),
                ('movie_poster', cloudinary.models.CloudinaryField(max_length=255, validators=[open_movie_data_base.movie.validators.validate_file_size])),
                ('movie_length', models.PositiveIntegerField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-uploaded_on'],
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, validators=[open_movie_data_base.utils.validators.CharValidator('^[A-Za-z\\w-]+\\Z', 'Use only latin letters, spaces and dashes')])),
            ],
            options={
                'verbose_name_plural': 'MovieGenres',
            },
        ),
    ]
