# Generated by Django 4.1.3 on 2022-12-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_actors_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_length',
            field=models.PositiveIntegerField(help_text='in minutes'),
        ),
    ]
