# Generated by Django 4.1.3 on 2022-11-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_moviegenres_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviegenres',
            options={'verbose_name_plural': 'MovieGenres'},
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
