# Generated by Django 4.1.3 on 2022-11-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['release_date']},
        ),
    ]
