# Generated by Django 4.1.3 on 2022-12-01 13:05

from django.db import migrations, models
import open_movie_data_base.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=50, validators=[open_movie_data_base.utils.validators.CharValidator('^[\\s\\w.-]+\\Z', 'Movie title may contain only latin letters, numbers, and dashes between characters.')]),
        ),
    ]
