# Generated by Django 4.1.3 on 2022-12-05 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-uploaded_on']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(error_messages={'max_length': 'Movie description can only be 600 characters', 'min_length': 'Movie description must be at least 150 characters'}, help_text='The first 30 characters will be displayed as short description', max_length=1200, validators=[django.core.validators.MinLengthValidator(300)]),
        ),
    ]
