# Generated by Django 4.1.3 on 2022-12-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_moviegenres_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-uploaded_on']},
        ),
    ]
