# Generated by Django 4.1.3 on 2022-12-06 06:25

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import open_movie_data_base.movie.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_options_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(error_messages={'max_length': 'Movie description can only be 1200 characters', 'min_length': 'Movie description must be at least 300 characters'}, help_text='The first 40 characters will be displayed as short description', max_length=1200, validators=[django.core.validators.MinLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[open_movie_data_base.movie.validators.validate_file_size]),
        ),
    ]
