# Generated by Django 4.1.3 on 2022-12-14 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(error_messages={'max_length': 'Movie description can only be 1200 characters', 'min_length': 'Movie description must be at least 300 characters'}, help_text='The first 250 characters will be displayed as short description', max_length=1600, validators=[django.core.validators.MinLengthValidator(300)]),
        ),
    ]
