# Generated by Django 4.1.3 on 2022-12-06 12:18

from django.db import migrations, models
import django.db.models.deletion
import open_movie_data_base.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AverageReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum_of_numbers', models.FloatField()),
                ('score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=600)),
                ('rating', models.FloatField(validators=[open_movie_data_base.common.validators.InRangeValidator(0.0, 10.0, 'Value must be between 0.0 and 10.0')])),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.review')),
            ],
        ),
    ]
