# Generated by Django 4.1.3 on 2022-11-24 16:36

from django.db import migrations, models
import open_movie_data_base.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=120)),
                ('rating', models.FloatField(validators=[open_movie_data_base.common.validators.InRangeValidator(0.0, 10.0, 'Value must be between 0.0 and 10.0')])),
            ],
        ),
    ]
