# Generated by Django 4.1.3 on 2022-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_averagereviewscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
