# Generated by Django 4.1.3 on 2022-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_averagereviewscore_total_sum_of_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagereviewscore',
            name='total_sum_of_numbers',
            field=models.FloatField(),
        ),
    ]
