version: '3.4'

services:
  web:
    image: everyonetm/omdb
    build: ./
    #    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn open_movie_data_base.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/home/app/web/tmp/open_movie_data_base/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: everyone
      POSTGRES_DB: open_movie_data_base
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web