# Generated by Django 4.1.3 on 2022-12-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_actor_profile_picture_moviedirector_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='type_of_user',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Actor', 'Actor'), ('MovieDirector', 'Movie Director')], default='', max_length=14),
        ),
    ]
