# Generated by Django 4.1.3 on 2022-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_appuser_type_of_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='type_of_user',
            field=models.CharField(choices=[('User', 'User'), ('Actor', 'Actor'), ('MovieDirector', 'Movie Director')], default='', max_length=14),
        ),
    ]
