# Generated by Django 4.1.3 on 2022-12-06 07:57

from django.db import migrations, models
import open_movie_data_base.user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_actor_description_moviedirector_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[open_movie_data_base.user.validators.names_validator]),
        ),
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[open_movie_data_base.user.validators.names_validator]),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[open_movie_data_base.user.validators.names_validator]),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[open_movie_data_base.user.validators.names_validator]),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[open_movie_data_base.user.validators.names_validator]),
        ),
        migrations.AlterField(
            model_name='regularuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[open_movie_data_base.user.validators.names_validator]),
        ),
    ]
